---

kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: &go registry.thobits.com/images/golang:1.21-alpine
    commands:
      - go build

  - name: test
    image: *go
    commands:
      - go test ./...

  - name: publish
    image: registry.thobits.com/images/drone-kaniko
    settings:
      auto_tag: true
      cache: true
      cache_repo: cache/drone-multipipeline-abort
      cache_ttl: 2h
      registry: registry.thobits.com
      repo: apps/drone-multipipeline-abort
    when:
      event:
        - tag
