---

services:
  plugin:
    build: .
    restart: unless-stopped
    environment:
      DRONE_SECRET: geheim
      DRONE_SERVER: http://app
    env_file: .env
    networks:
      - drone

networks:
  drone:
    external: true
    name: drone-webhook
