---

services:
  plugin:
    build: .
    restart: unless-stopped
    environment:
      DRONE_SECRET: geheim
    networks:
      drone:
        ipv4_address: 192.168.72.128

networks:
  drone:
    external: true
    name: drone-webhook
